### ISSUE TITLE
error on appscan-sast-action/src/saclientutil.js

### ISSUE THREAD

**Issue by OsTarek** [HCL-TECH-SOFTWARE/appscan-sast-action#16]
Faced an execution error:
```
if(fs.e(zipFile)) {
    fs.unlinkSync(zipFile);
}
```
 Line 74: TypeError: fs.e is not a function

I believe it should probably be replaced with

```
if(fs.existsSync(zipFile)) {
    fs.unlinkSync(zipFile);
}
```

**Comment by mattmurp** [comment]
Thanks for opening this issue. This is corrected by https://github.com/HCL-TECH-SOFTWARE/appscan-sast-action/pull/17
