### ISSUE TITLE
Node 16 Deprecation Warning

### ISSUE THREAD

**Issue by Anhgrew** [HCL-TECH-SOFTWARE/appscan-sast-action#33]
**Describe the bug**
The GitHub Actions workflow is generating a deprecation warning due to the use of Node.js 16. GitHub Actions now requires the use of Node.js 20, as Node.js 16 actions have been deprecated.

**To Reproduce**

Go to the GitHub repository containing the workflow.
Run the GitHub Actions workflow.
Observe the deprecation warning in the workflow logs.
The warning specifically mentions the use of Node.js 16 in `HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.3`

**Expected behavior**
The expected behavior is for the GitHub Actions workflow to run without any deprecation warnings. It should use the updated Node.js 20 environment for all actions.

**Screenshots**
![image](https://github.com/HCL-TECH-SOFTWARE/appscan-sast-action/assets/47881661/41e4d541-3c25-45cb-b423-1d10826b4cf8)

**Additional context**
The deprecation of Node.js 16 actions is part of GitHub's ongoing maintenance and update of their Actions infrastructure. More information about this transition can be found at: [GitHub Blog Changelog](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

**Comment by mattmurp** [comment]
Thanks for opening the issue. We have released version 1.0.4 which uses Node.js 20.
